apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: idc

profiles:
- name: develop
  activation:
  - kubeContext: k3d
  build:
    artifacts:
    - image: datacube
      context: ../tb4mmaggots/datacube
  deploy:
    helm:
      releases:
      - name: dc
        namespace: dc
        chartPath: ./charts/datacube
        valuesFiles: ["./charts/datacube/env/values-dev.yaml"]
        artifactOverrides:
          datacube:
              image: datacube

- name: prod
  activation:
  - kubeContext: arn:aws
  deploy:
    helm:
      releases:
      - name: dc
        namespace: dc
        createNamespace: true
        chartPath: ./charts/datacube
        valuesFiles: ["./charts/datacube/env/values-prod.yaml"]
