apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{.Values.namespace}}
  name: {{.Values.database.name}}
spec:
  selector:
    matchLabels:
      app: {{.Values.database.name}}
  template:
    metadata:
      labels:
        app: {{.Values.database.name}}
    spec:
      # nodeSelector:
      #   Type: {{.Values.database.nodeSelectorType}}
      # tolerations:
      # - key: "proces_type"
      #   operator: "Equal"
      #   value: "proces"
      #   effect: "NoSchedule"
      containers:
      - name: {{.Values.database.name}}
        image: {{.Values.database.image}}
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dc-db-creds
              key: dc-psw
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: dc-db-creds
              key: dc-user
        resources:
          limits:
            memory: "500Mi"
            # cpu: "100m"
        ports:
        - containerPort: {{.Values.database.port}}
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{.Values.namespace}}
  name: {{.Values.database.name}}
spec:
  type: ClusterIP
  selector:
    app: {{.Values.database.name}}
  ports:
    - protocol: TCP
      port: {{.Values.database.port}}
      targetPort: {{.Values.database.port}}