apiVersion: v1
kind: Secret
metadata:
  name: dc-db-creds
  namespace: {{.Values.namespace}}
type: Opaque
data:
  dc-user: {{.Values.database.user | b64enc}}
  dc-psw: {{.Values.database.psw | b64enc}}
  dc-db: {{.Values.database.dbName | b64enc}}
